### ISSUE TITLE
Problema en separar palabras

### ISSUE THREAD

**Issue by eduardoacye** [uson-ia/maquinas-busqueda#1]
Si corro el código de la rama _collective-intelligence_ no va a producir errores (al menos no ha producido con las páginas que he intentado).

Sin embargo en el método `separatewords` de la clase `crawler` en el archivo `searchengine.py` el método para la separación de una cadena en palabras no funciona cuando la cadena contiene acentos (funciona bien cuando tiene puros caracteres ascii).

¿Alguien se avienta la arreglada de este mal flow?

```
In [1]: text = "un avión"

In [2]: [s.lower() for s in splitter.split(text) if s != '']
Out[2]: ['un', 'avi', 'n']
```

**Comment by geratarra** [comment]
no he llegado a esa funcion aun pero.. hacer `text.split()` separa las palabras que no ??

**Comment by eduardoacye** [comment]
Si Gera, la bronca es el encoding de la cadena, ingresa el ejemplo que puse en el REPL del ipython

edit: Había leído mal tu comentario, si `text.split()` separa correctamente las palabras aunque tengan acentos, haz la corrección y cierra este issue C:

**Comment by geratarra** [comment]
no funciona el split :(, lo probe con "http://es.wikipedia.org"  y me dio error por una letra "ẽ", cambie la funcion por la original y si corrio bien ..

**Comment by eduardoacye** [comment]
Hmmm, ahorita me pondré a checarlo. El punto es hacer un split por whitespace en un texto en un encoding arbitrario. Algo que quizá estaría macanoide sería hacer un parseo inicial de la página tomando todo como si fuera ascii normalón y de ahi detectar el encoding del documento, luego en caso que sea utf o latin o iso, etc hacemos un parseo tomando el contenido como tal. Eso lo propuso el profe pero yo no he tirado código al respecto...

Necesitamos mas manos para cerrar todos los issues y terminar el page rank para mañana.

**Comment by eduardoacye** [comment]
Ahorita estoy en una compu sin git ni ipython ni emacs, pero estoy instalando todo.

Les comparto este snippet de código que me sirvió con el ejemplo del avión y la ẽ si alguien hace la prueba incorporándo la modificación en el codebase que tenemos y jala, pues que modifique el código paro

```
In [1]: import re

In [2]: splitter = re.compile(ur'\W*', re.UNICODE)

In [3]: splitter.split(u'Un avión muy grande')
Out[3]: [u'Un', u'avi\xf3n', u'muy', u'grande']

In [4]: splitter.split(u'将軍 Português Tiếng Việt  فارسی ẽẽẽ ẽẽ')
Out[4]: 
[u'\u5c06\u8ecd',
 u'Portugu\xeas',
 u'Ti\u1ebfng',
 u'Vi\u1ec7t',
 u'\u0641\u0627\u0631\u0633\u06cc',
 u'\u1ebd\u1ebd\u1ebd',
 u'\u1ebd\u1ebd']
```
