### ISSUE TITLE
Problema con manejo de consultas fallidas

### ISSUE THREAD

**Issue by eduardoacye** [uson-ia/maquinas-busqueda#3]
En el método `getmatchrows` de la clase `searcher` no se manejan posibles errores por no encontrar alguna palabra de la consulta en la base de datos.

Otro bicho por arreglar.

**Comment by geratarra** [comment]
Agregue un bloque "try", por lo pronto ..

**Comment by eduardoacye** [comment]
Está bien, luego habrá que refinar mejor la solución ya que ese bloque de código va a fallar si no se ha leído una palabra y hacemos una consulta que la contenga (lo cuál está muy mequetrefoidus (por ejemplo la palabra mequetrefoidus no da resultados en el buscador de google)).
