### ISSUE TITLE
División por cero en métrica link_text_score

### ISSUE THREAD

**Issue by eduardoacye** [uson-ia/maquinas-busqueda#6]
Hay un error o una condición sin manejar en la función link_text_score. Es una división por cero, el que se la quiera comer que le entre.

La tirada es que el máximo de los link_scores es cero y al momento de normalizar vale roña.

**Comment by eduardoacye** [comment]
Por mientras la quitaré de la ponderación

**Comment by cruzluquejm** [comment]
Listo ;)
